package pe.exirium.demo.exception

class UserNotFoundException(message: String) : RuntimeException(message)